/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPRESubscriptionManager,
  IPRESubscriptionManagerInterface,
} from "../IPRESubscriptionManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes16",
        name: "_policyId",
        type: "bytes16",
      },
      {
        internalType: "address",
        name: "_policyOwner",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "_size",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "_startTimestamp",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_endTimestamp",
        type: "uint32",
      },
    ],
    name: "createPolicy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes16",
        name: "_policyID",
        type: "bytes16",
      },
    ],
    name: "getPolicy",
    outputs: [
      {
        components: [
          {
            internalType: "address payable",
            name: "sponsor",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "startTimestamp",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "endTimestamp",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "size",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
        ],
        internalType: "struct IPRESubscriptionManager.Policy",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_size",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "_startTimestamp",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "_endTimestamp",
        type: "uint32",
      },
    ],
    name: "getPolicyCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes16",
        name: "_policyID",
        type: "bytes16",
      },
    ],
    name: "isPolicyActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes16",
        name: "_policyId",
        type: "bytes16",
      },
    ],
    name: "revokePolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPRESubscriptionManager__factory {
  static readonly abi = _abi;
  static createInterface(): IPRESubscriptionManagerInterface {
    return new utils.Interface(_abi) as IPRESubscriptionManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPRESubscriptionManager {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPRESubscriptionManager;
  }
}
