/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type ArrangementInfoStruct = {
  node: string;
  indexOfDowntimePeriods: BigNumberish;
  lastRefundedPeriod: BigNumberish;
};

export type ArrangementInfoStructOutput = [string, BigNumber, number] & {
  node: string;
  indexOfDowntimePeriods: BigNumber;
  lastRefundedPeriod: number;
};

export type PolicyStruct = {
  disabled: boolean;
  sponsor: string;
  owner: string;
  feeRate: BigNumberish;
  startTimestamp: BigNumberish;
  endTimestamp: BigNumberish;
  reservedSlot1: BigNumberish;
  reservedSlot2: BigNumberish;
  reservedSlot3: BigNumberish;
  reservedSlot4: BigNumberish;
  reservedSlot5: BigNumberish;
  arrangements: ArrangementInfoStruct[];
};

export type PolicyStructOutput = [
  boolean,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  ArrangementInfoStructOutput[]
] & {
  disabled: boolean;
  sponsor: string;
  owner: string;
  feeRate: BigNumber;
  startTimestamp: BigNumber;
  endTimestamp: BigNumber;
  reservedSlot1: BigNumber;
  reservedSlot2: BigNumber;
  reservedSlot3: BigNumber;
  reservedSlot4: BigNumber;
  reservedSlot5: BigNumber;
  arrangements: ArrangementInfoStructOutput[];
};

export interface IPolicyManagerInterface extends utils.Interface {
  functions: {
    "createPolicy(bytes16,address,uint64,address[])": FunctionFragment;
    "policies(bytes16)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [BytesLike, string, BigNumberish, string[]]
  ): string;
  encodeFunctionData(functionFragment: "policies", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;

  events: {};
}

export interface IPolicyManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPolicyManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPolicy(
      _policyId: BytesLike,
      _policyOwner: string,
      _endTimestamp: BigNumberish,
      _nodes: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    policies(
      _policyId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createPolicy(
    _policyId: BytesLike,
    _policyOwner: string,
    _endTimestamp: BigNumberish,
    _nodes: string[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  policies(
    _policyId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createPolicy(
      _policyId: BytesLike,
      _policyOwner: string,
      _endTimestamp: BigNumberish,
      _nodes: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    policies(
      _policyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PolicyStructOutput>;
  };

  filters: {};

  estimateGas: {
    createPolicy(
      _policyId: BytesLike,
      _policyOwner: string,
      _endTimestamp: BigNumberish,
      _nodes: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    policies(
      _policyId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPolicy(
      _policyId: BytesLike,
      _policyOwner: string,
      _endTimestamp: BigNumberish,
      _nodes: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    policies(
      _policyId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
