/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type PolicyStruct = {
  sponsor: string;
  startTimestamp: BigNumberish;
  endTimestamp: BigNumberish;
  size: BigNumberish;
  owner: string;
};

export type PolicyStructOutput = [string, number, number, number, string] & {
  sponsor: string;
  startTimestamp: number;
  endTimestamp: number;
  size: number;
  owner: string;
};

export interface IPRESubscriptionManagerInterface extends utils.Interface {
  functions: {
    "createPolicy(bytes16,address,uint16,uint32,uint32)": FunctionFragment;
    "getPolicy(bytes16)": FunctionFragment;
    "getPolicyCost(uint16,uint32,uint32)": FunctionFragment;
    "isPolicyActive(bytes16)": FunctionFragment;
    "revokePolicy(bytes16)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [BytesLike, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicyCost",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPolicyActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePolicy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPolicyCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPolicyActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokePolicy",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPRESubscriptionManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPRESubscriptionManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPolicy(
      _policyId: BytesLike,
      _policyOwner: string,
      _size: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPolicy(
      _policyID: BytesLike,
      overrides?: CallOverrides
    ): Promise<[PolicyStructOutput]>;

    getPolicyCost(
      _size: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isPolicyActive(
      _policyID: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    revokePolicy(
      _policyId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  createPolicy(
    _policyId: BytesLike,
    _policyOwner: string,
    _size: BigNumberish,
    _startTimestamp: BigNumberish,
    _endTimestamp: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPolicy(
    _policyID: BytesLike,
    overrides?: CallOverrides
  ): Promise<PolicyStructOutput>;

  getPolicyCost(
    _size: BigNumberish,
    _startTimestamp: BigNumberish,
    _endTimestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isPolicyActive(
    _policyID: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  revokePolicy(
    _policyId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createPolicy(
      _policyId: BytesLike,
      _policyOwner: string,
      _size: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getPolicy(
      _policyID: BytesLike,
      overrides?: CallOverrides
    ): Promise<PolicyStructOutput>;

    getPolicyCost(
      _size: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPolicyActive(
      _policyID: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    revokePolicy(
      _policyId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    createPolicy(
      _policyId: BytesLike,
      _policyOwner: string,
      _size: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPolicy(
      _policyID: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPolicyCost(
      _size: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPolicyActive(
      _policyID: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revokePolicy(
      _policyId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPolicy(
      _policyId: BytesLike,
      _policyOwner: string,
      _size: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPolicy(
      _policyID: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPolicyCost(
      _size: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPolicyActive(
      _policyID: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revokePolicy(
      _policyId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
