name: "Build and Deploy Client"
on:
  push:
    paths:
      - "client/**"
    branches:
      - main

jobs:
  BUILD_SERVER:
    runs-on: ["self-hosted", "X64", "Linux"]
    steps:
      - name: own
        run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/opendrm-poc
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          make client/build
          make client/push
          make client/clean
  DEPLOY_SERVER:
    runs-on: ["self-hosted", "X64", "Linux"]
    needs: BUILD_SERVER
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        run: |
          make client/deploy TAG=$(git rev-parse HEAD) ADDRESS=http://nomad.masterfiledev.service
